awwblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap #this
from blog.sitemaps import PostSitemap #this
from rest_framework.authtoken import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

#this
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', include('blog.urls', namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'), #this
    path('api/v1/',include("blog.api.urls", namespace="blog_api")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns=[
    path('',views.post_list,name="post_list"),
    # path('<slug:slug>/',views.PostDetail.as_view(),name="post_detail"),
    path('<slug:post>/',views.post_detail,name="post_detail"),
    path('comment/reply/', views.reply_page, name="reply"),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_tag'), #this
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>AwwBlog{% block title %}{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- static file -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <script src="{% static 'js/main.js'%}"></script>

    <!-- highlight js -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/monokai-sublime.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <a class="navbar-brand" href="/">AwwBlog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

     

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/tag/linux/' %}active{% endif %}" aria-current="page" href="{{ request.scheme }}://{{ request.get_host }}/tag/linux/">Linux</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/tag/tips/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/tips/">Tips</a>
          </li>
         
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tutorial
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item {% if request.path == '/tag/python/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/python/">Python</a>
            </li>
            
            <li>
              <a class="dropdown-item {% if request.path == '/tag/django/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/django/">Django</a>
            </li>
          
          </ul>
        </li>

        </ul>
        <form class="d-flex" action="/">
          <input class="form-control mr-0" type="search" value="{{request.GET.q}}" name="q" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
    
    <main class="container my-3">
        
        <h2 class="my-3">
          {% if request.GET.q is not null %}
            Search Results for "{{ request.GET.q }}"
          {% endif %}
        </h2>

        {% block content %}

        {% endblock content %}
    </main>
  <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

</body>
</html>

templates/comment.html
<div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">

        <div class="mt-3">
            <strong>{{comment.name}}</strong> 
            {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
            <small class="text-muted">On {{ comment.created.date }}</small>
        </div>
        <div class="border p-2 rounded">
            <p>{{comment.body}}</p>
            <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
        
            <div id="reply-form-container-{{comment.id}}" style="display:none">
            
                <form method="post" action="{% url 'blog:reply' %}" class="mt-3">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{post.id}}">
                    <input type="hidden" name="parent" value="{{comment.id}}">
                    <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">


                    {{comment_form.as_p}}

                    <div>
                        <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        {% for comment in comment.get_comments %}
            {% include 'comment.html' with comment=comment %}
        {% endfor %}
</div>

templates/pagination.html
{% if page.has_other_pages %}
  <ul class="pagination mt-3 mb-0">
    {% if page.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

templates/post_detail.html
{% extends 'base.html' %}

{% block title %} - {{post.title}}{% endblock title %}

{% block content %}
<article>
    <figure>
        <img src="{{ post.image.url }}" class="rounded" alt="{{post.title}}">
    </figure>

    <div class="mt-3">
        <h1>{{post.title}}</h1>
        <p class="text-muted">
            Published {{ post.publish.date }} by <strong>{{ post.author }}</strong>
        </p>
    </div>

    <div class="article-body">
        {{post.body|safe}}
    </div>

    <p>
        <strong>Tags:</strong>
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_tag' tag.slug %}" class="link-light text-decoration-none badge bg-secondary">
            {{tag.name}}
        </a>
        <!-- {% if not forloop.last %}, {% endif %} -->
        {% endfor %}
    </p>

</article>

<hr />

<div class="my-3">
    <h3>Similar Posts</h3>
</div>
<div class="row">
    {% for post in similar_posts %}
    <div class="col-md-6 col-sm-6 col-lg-4 mb-3">
        <div class="card border-0">
            <div class="ratio ratio-16x9">
                <img src="{{ post.image.url }}" class="rounded featured-image-list" alt="{{post.title}}">
            </div>
            <div class="card-body p-0 m-0 mt-2">
                <h2 class="card-title h6 my-0 py-0">
                    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                </h2>
                <p class="card-text">
                    <small class="text-muted">
                        <span>{{post.publish.date}} by
                            <b>{{post.author}}</b></span>

                        <!-- <a href="" class="badge badge-light text-muted">{{post.tags.all|join:" "}}</a> -->


                    </small>
                </p>
                <!-- <p>{{post.body|truncatechars:100|linebreaks}}</p> -->
            </div>
        </div>
    </div>
    {% empty %}
    <p class="text-muted">There is no similar post yet</p>
    {% endfor %}
</div>




<hr />
<h3>Add Comment</h3>
<form method="post" action="">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit" class="btn btn-primary">Comment</button>
</form>


{% with comments.count as total_comments %}
<h3 class="mt-5">
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h3>
{% endwith %}

{% if not post.comments.all %}
No comments yet

{% else %}
{% for comment in post.get_comments %}
{% include 'comment.html' with comment=comment %}
{% endfor %}
{% endif %}

{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}
{% if tag %}
<h2 class="mb-3">Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
<div class="card mb-3">
    <div class="card-body">
        <div class="row g-0">
            <div class="col-md-5">
                <div class="ratio ratio-16x9">
                    <img src="{{ post.image.url }}" class="rounded featured-image-list" alt="{{post.title}}">
                </div>
            </div>
            <div class="col-md-7 ps-md-3 pt-3 pt-md-0 d-flex flex-column">

                <h2 class="card-title h5">
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>

                <div class="text-muted">
                    <small>
                        Published {{ post.publish.date }} by <strong>{{ post.author }}</strong>
                    </small>
                </div>


                <p class="card-text mb-auto py-2">{{ post.body|safe|striptags|truncatechars:100 }}</p>


                <div>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary btn-sm">Read more</a>
                </div>

            </div>
        </div>
    </div>
</div>

{% endfor %}

{% include "pagination.html" with page=posts %}



{% endblock content %}